# https://docs.astral.sh/ruff/rules/

select = [ "ALL" ]

ignore = [
    # Pyflakes (F)
    # https://docs.astral.sh/ruff/rules/#pyflakes-f

    # pycodestyle (E, W)
    # https://docs.astral.sh/ruff/rules/#pycodestyle-e-w
    # "W191",
    # "E501",
    # "E722",

    # isort (I)
    # https://docs.astral.sh/ruff/rules/#isort-i
    # "I001",

    # pydocstyle (D)
    # https://docs.astral.sh/ruff/rules/#pydocstyle-d
    # "D100",
    # "D102",
    # "D103",
    # "D107",
    # "D204",
    # "D208",
    # "D419",
    # "D400",
    # "D415",
    # "D210",
    # "D206",
    # "D202",

    # flake8-annotations (ANN)
    # https://docs.astral.sh/ruff/rules/#flake8-annotations-ann
    # "ANN001",
    # "ANN002",
    # "ANN101",
    # "ANN201",
    # "ANN202",
    # "ANN204",

    # flake8-commas (COM)
    # https://docs.astral.sh/ruff/rules/#flake8-commas-com
    # "COM812",

    # flake8-print (T20)
    # https://docs.astral.sh/ruff/rules/#flake8-print-t20
    # "T201",

    # flake8-quotes (Q)
    # https://docs.astral.sh/ruff/rules/#flake8-quotes-q
    # "Q000",

    # flake8-return (RET)
    # https://docs.astral.sh/ruff/rules/#flake8-return-ret
    # "RET505",
    # "RET504",
    # "RET503",

    # flake8-todos (TD)
    # https://docs.astral.sh/ruff/rules/#flake8-todos-td
    # "TD001",
    # "TD002",
    # "TD003",

    # flake8-fixme (FIX)
    # https://docs.astral.sh/ruff/rules/#flake8-fixme-fix
    # "FIX001",
    # "FIX002",

    # eradicate (ERA)
    # https://docs.astral.sh/ruff/rules/#eradicate-era
    # "ERA001",

    # Pylint (PL)
    # https://docs.astral.sh/ruff/rules/#pylint-pl
    # "PLR2004",

    # Ruff-specific rules (RUF)
    # https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf
    # "RUF001",
    # "RUF002",
    # "RUF003",
]

# ignore = [ "W191" ]
