select = [ "ALL" ]

ignore = [
    "W191",
    "RUF001",
    "RUF002",
    "RUF003",
    "E501",
    "E722",
    "ANN001",
    "ANN002",
    "ANN101",
    "ANN201",
    "ANN202",
    "ANN204",
    "D100",
    "D102",
    "D103",
    "D107",
    "D204",
    "D208",
    "D419",
    "D400",
    "D415",
    "D210",
    "D206",
    "D202",
    "TD001",
    "TD002",
    "TD003",
    "FIX001",
    "FIX002",
    "PLR2004",
    "T201",
    "ERA001",
    "Q000",
    "RET505",
    "RET504",
    "RET503",
    "I001",
    "COM812"
]

# ignore = [ "W191" ]
