# Separate config for work with docstrings
# https://docs.astral.sh/ruff/configuration/
# https://docs.astral.sh/ruff/rules/

# select = [
#     "ALL"
# ]

select = [
    # doc-line-too-long
    "W505",
    # pydocstyle (D) [103]
    "D",
    # f-string used as docstring. Python will interpret this as a joined string, rather than a docstring.
    "B021",
    # Docstrings should not be included in stubs
    "PYI021",
    # Single quote docstring found but double quotes preferred
    "Q002",
    # Docstring contains ambiguous {}. Did you mean {}?
    "RUF002",
]

# ignore = [

# ]

# ignore = [ "W191" ]
