# https://docs.astral.sh/ruff/configuration/
# https://docs.astral.sh/ruff/rules/

select = [
    "ALL"
]

ignore = [
    # incompatible checks
    # "D203", https://docs.astral.sh/ruff/rules/one-blank-line-before-class/
    # "D211", https://docs.astral.sh/ruff/rules/blank-line-before-class/
    "D203",
    # "D212", https://docs.astral.sh/ruff/rules/multi-line-summary-first-line/
    # "D213", https://docs.astral.sh/ruff/rules/multi-line-summary-second-line/
    "D213",

    # Pyflakes (F)
    # https://docs.astral.sh/ruff/rules/#pyflakes-f

    # pycodestyle (E, W) [515, 39, 1]
    # https://docs.astral.sh/ruff/rules/#pycodestyle-e-w
    "W191",

    "E501",
    "E722",

    # isort (I) [5]
    # https://docs.astral.sh/ruff/rules/#isort-i
    "I001",

    # pydocstyle (D) [103]
    # https://docs.astral.sh/ruff/rules/#pydocstyle-d
    # [7, 19, 16, 1]
    "D100",
    "D102",
    "D103",
    "D107",

    # [1, 1, 3, 9, 7]
    "D202",
    "D204",
    "D206",
    "D208",
    "D210",

    # [16, 16, 7]
    "D400",
    "D415",
    "D419",

    # pyupgrade (UP) [1]
    # https://docs.astral.sh/ruff/rules/#pyupgrade-up
    "UP015",

    # flake8-annotations (ANN) [121]
    # https://docs.astral.sh/ruff/rules/#flake8-annotations-ann
    # [41, 1, 20, 49, 9, 1]
    "ANN001",
    "ANN002",
    "ANN101",
    "ANN201",
    "ANN202",
    "ANN204",

    # flake8-boolean-trap (FBT) [2, 4]
    # https://docs.astral.sh/ruff/rules/#flake8-boolean-trap-fbt
    "FBT002",
    "FBT003",

    # flake8-commas (COM) [1]
    # https://docs.astral.sh/ruff/rules/#flake8-commas-com
    "COM812",

    # flake8-print (T20) [17]
    # https://docs.astral.sh/ruff/rules/#flake8-print-t20
    "T201",

    # flake8-quotes (Q) [8]
    # https://docs.astral.sh/ruff/rules/#flake8-quotes-q
    "Q000",

    # flake8-return (RET) [1, 2, 8]
    # https://docs.astral.sh/ruff/rules/#flake8-return-ret
    "RET503",
    "RET504",
    "RET505",

    # flake8-use-pathlib (PTH) [1, 1, 1, 1, 4]
    # https://docs.astral.sh/ruff/rules/#flake8-use-pathlib-pth
    "PTH107",
    "PTH109",
    "PTH112",
    "PTH113",
    "PTH123",

    # flake8-todos (TD) [8, 28, 26]
    # https://docs.astral.sh/ruff/rules/#flake8-todos-td
    "TD001",
    "TD002",
    "TD003",

    # flake8-fixme (FIX) [8, 20]
    # https://docs.astral.sh/ruff/rules/#flake8-fixme-fix
    "FIX001",
    "FIX002",

    # eradicate (ERA) [39]
    # https://docs.astral.sh/ruff/rules/#eradicate-era
    "ERA001",

    # Pylint (PL) [15]
    # https://docs.astral.sh/ruff/rules/#pylint-pl
     # [1, 1, 10, 1, 2]
    "PLR0915",
    "PLR1714",
    "PLR2004",
    "PLW0603",
    "PLW2901",

    # Perflint (PERF) [1]
    # https://docs.astral.sh/ruff/rules/#perflint-perf
    "PERF401",

    # Ruff-specific rules (RUF) [3, 10, 38]
    # https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf
    "RUF001",
    "RUF002",
    "RUF003",
]

# ignore = [ "W191" ]
